from machine import Pin
from time import sleep

led1 = Pin(0, Pin.OUT)
led2 = Pin(1, Pin.OUT)
led3 = Pin(2, Pin.OUT)
led4 = Pin(3, Pin.OUT)
led5 = Pin(4, Pin.OUT)
led6 = Pin(5, Pin.OUT)
led7 = Pin(6, Pin.OUT)
led8 = Pin(7, Pin.OUT)
led9 = Pin(8, Pin.OUT)
led10 = Pin(9, Pin.OUT)
led11 = Pin(10, Pin.OUT)
led12 = Pin(11, Pin.OUT)

timeskip = 0.025

led1.on()
led2.on()
led3.on()
led4.on()
led5.on()
led6.on()
led7.on()
led8.on()
led9.on()
led10.on()
led11.on()
led12.on()
    
sleep(2)
   
led1.off()
led2.off()
led3.off()
led4.off()
led5.off()
led6.off()
led7.off()
led8.off()
led9.off()
led10.off()
led11.off()
led12.off()
  
    
sleep(1)

while True:
    
    
    led1.on()
    sleep(timeskip)
    led2.on()
    sleep(timeskip)
    led3.on()
    sleep(timeskip)
    led4.on()
    sleep(timeskip)
    led1.off()
    sleep(timeskip)
    led5.on()
    sleep(timeskip)
    led2.off()
    sleep(timeskip)
    led6.on()
    sleep(timeskip)
    led3.off()
    sleep(timeskip)
    led7.on()
    sleep(timeskip)
    led4.off()
    sleep(timeskip)
    led8.on()
    sleep(timeskip)
    led5.off()
    sleep(timeskip)
    led9.on()
    sleep(timeskip)
    led6.off()
    sleep(timeskip)
    led10.on()
    sleep(timeskip)
    led7.off()
    sleep(timeskip)
    led11.on()
    sleep(timeskip)
    led8.off()
    sleep(timeskip)
    led12.on()
    sleep(timeskip)
    led8.off()
    sleep(timeskip)
    led9.off()
    sleep(timeskip)
    led10.off()
    sleep(timeskip)
    led11.off()
    sleep(timeskip)
    led12.off()
    sleep(timeskip)
